<?php

/**
 * @file
 * Base file for the render_patterns module.
 *
 */

use Drupal\Core\Render\Markup;
use Drupal\render_patterns\MissingPatternException;
use Drupal\render_patterns\PatternException;
use Drupal\render_patterns\PatternInterface;

/**
 * Factory function to generate a new pattern instance.
 *
 * @param string $pattern_name
 *   The name of the pattern.
 * @param array $preset_values
 *   An array of property/values to set on the new pattern.
 *
 * @return \Drupal\render_patterns\PatternInterface
 *   The pattern instance.
 *
 * @see \Drupal\render_patterns\Pattern::get
 *
 * @deprecated Use the ::get() method on the render pattern class.
 */
function render_patterns_get(string $pattern_name, array $preset_values = []): PatternInterface {
  try {
    $candidates = array_map(function ($name) {
      return 'Drupal\\render_patterns\\Pattern\\' . $name;
    }, array_unique([
      $pattern_name . 'RenderPattern',
      $pattern_name,
    ]));

    foreach ($candidates as $class_name) {
      if (class_exists($class_name)) {
        return $class_name::get($preset_values);
      }
    }

    throw new MissingPatternException($candidates);
  }
  catch (\Exception $exception) {
    $message = $exception->getMessage();
    if (!$exception instanceof PatternException) {
      $message = t('%name: @message', [
        '%name' => $pattern_name,
        '@message' => $message,
      ])->__toString();
    }
    \Drupal::messenger()->addError(Markup::create($message));
    throw new \RuntimeException($message, $exception->getCode(), $exception);
  }
}

/**
 * Implements hook_render_patterns_info().
 *
 * Automatically register the default theme as providing render patterns based
 * on the existence of the directory.
 */
function render_patterns_render_patterns_info_alter(&$info) {
  $themes = \Drupal::service('extension.list.theme')->getList();
  $default_theme_name = \Drupal::service('config.factory')
    ->get('system.theme')
    ->get('default');
  foreach ($themes as $theme) {
    $theme_folder = drupal_get_path('theme', $theme->getName()) . '/src/render_patterns';
    if (is_dir(\Drupal::root() . '/' . $theme_folder)) {
      $info[$theme->getName()] = [
        'directory' => $theme_folder,
        // Give the default theme the trump weight.
        'weight' => $default_theme_name === $theme->getName() ? 10 : 0,
      ];
    }
  }
}
